# Генератор NUnit-тестов на основе YAML-спецификации

import yaml
import argparse
import re
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any

TEST_FILE_TEMPLATE = '''// ============================================================
// AUTO-GENERATED TESTS. DO NOT EDIT MANUALLY.
// Generated by: generator/gen_tests.py
// Source spec: {spec_source}
// Generation date: {generation_date}
// ============================================================

using NUnit.Framework;
using {interface_namespace};

namespace {test_namespace}
{{
    [TestFixture]
    [Description("Automatically generated tests for {module_name} based on formal spec")]
    public class {module_name}GeneratedTests
    {{
        private IMathExpressionEvaluator _sut;

        [SetUp]
        public void SetUp()
        {{
            _sut = new {implementation_class}();
        }}

{test_methods}
    }}
}}
'''

TEST_METHOD_TEMPLATE = '''
        #region {method_name} - {case_desc}

        [Test]
        [Description("{case_desc}")]
        {category_attributes}
        public void {method_name}_{case_name}()
        {{
{act_assert_code}
        }}

        #endregion
'''

def load_spec(spec_path: str) -> Dict[str, Any]:
    with open(spec_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def load_config(config_path: str) -> Dict[str, Any]:
    with open(config_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def format_csharp_input(value: Any) -> str:
    """Преобразует значение в C#-литерал"""
    if value is None:
        return "null"
    if isinstance(value, str):
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return str(value)

def sanitize_name(text: str) -> str:
    """Очищает текст для использования в имени метода"""
    # Заменяем все не-буквенно-цифровые символы на подчеркивания
    cleaned = re.sub(r'[^a-zA-Z0-9а-яА-Я]', '_', text)
    # Убираем множественные подчеркивания
    cleaned = re.sub(r'_+', '_', cleaned)
    # Убираем подчеркивания в начале и конце
    cleaned = cleaned.strip('_')
    # Ограничиваем длину
    if len(cleaned) > 50:
        cleaned = cleaned[:50]
    return cleaned

def generate_category_attributes(tags: List[str]) -> str:
    """Генерирует отдельные атрибуты Category для каждого тега"""
    if not tags:
        return ""
    attributes = '\n        '.join(f'[Category("{tag}")]' for tag in tags)
    return attributes

def generate_test_method(method_data: Dict[str, Any], eq_class: Dict[str, Any], 
                          config: Dict[str, Any]) -> str:
    method_name = method_data["name"]
    inputs_list = eq_class.get("inputs", [])
    
    # Форматируем входные параметры для вызова метода
    inputs_str = ", ".join(format_csharp_input(inp) for inp in inputs_list)
    
    # Формируем имя теста из описания
    case_desc = eq_class["case"]
    case_name = sanitize_name(case_desc)
    
    # Формируем теги (categories) - отдельные атрибуты
    tags = eq_class.get("tags", [])
    category_attributes = generate_category_attributes(tags)
    
    # Проверяем ожидается ли исключение
    expected_exception = eq_class.get("expected_exception")
    expected_message = eq_class.get("expected_message", "")
    
    if expected_exception:
        # Тест на исключение
        act_assert_code = f'''            // Act & Assert
            var exception = Assert.Throws<{expected_exception}>(() => _sut.{method_name}({inputs_str}));
            Assert.That(exception.Message, Does.Contain("{expected_message}").Or.Empty);'''
    else:
        # Обычный тест
        expected = eq_class.get("expected")
        if expected is not None:
            precision = config.get("generation", {}).get("precision", "1e-10")
            act_assert_code = f'''            // Act
            double result = _sut.{method_name}({inputs_str});

            // Assert
            Assert.That(result, Is.EqualTo({expected}).Within({precision}));'''
        elif eq_class.get("expected_result_type") == "не падает":
            act_assert_code = f'''            // Act & Assert
            Assert.DoesNotThrow(() => _sut.{method_name}({inputs_str}));'''
        else:
            act_assert_code = f'''            // Act
            double result = _sut.{method_name}({inputs_str});'''
    
    return TEST_METHOD_TEMPLATE.format(
        method_name=method_name,
        case_desc=case_desc,
        case_name=case_name,
        category_attributes=category_attributes,
        act_assert_code=act_assert_code
    )

def generate_all_tests(spec: Dict[str, Any], config: Dict[str, Any]) -> str:
    all_methods = []
    
    for method in spec.get("methods", []):
        eq_classes = method.get("equivalence_classes", [])
        
        for eq_class in eq_classes:
            test_method = generate_test_method(method, eq_class, config)
            all_methods.append(test_method)
    
    return "\n".join(all_methods)

def save_tests(content: str, config: Dict[str, Any], spec: Dict[str, Any]) -> None:
    output_dir = Path(config.get("output_dir", "tests/Generated"))
    output_dir.mkdir(parents=True, exist_ok=True)
    
    module_name = spec["module"]
    output_file = output_dir / f"{module_name}Tests.Generated.cs"
    
    test_namespace = config.get("test_namespace", "Lab1_MathEvaluator.Tests.Generated")
    interface_namespace = config.get("interface_namespace", "Lab1_MathEvaluator.Tests.Interfaces")
    implementation_class = config.get("default_implementation", "MathExpressionEvaluator")
    
    full_content = TEST_FILE_TEMPLATE.format(
        spec_source=config.get("spec_path", "N/A"),
        generation_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        module_name=module_name,
        test_namespace=test_namespace,
        interface_namespace=interface_namespace,
        implementation_class=implementation_class,
        test_methods=content
    )
    
    output_file.write_text(full_content, encoding="utf-8")
    print(f"[√] Сгенерирован файл: {output_file}")
    print(f"    - Методов в спецификации: {len(spec.get('methods', []))}")
    print(f"    - Сгенерировано тестов: {sum(len(m.get('equivalence_classes', [])) for m in spec.get('methods', []))}")

def main():
    parser = argparse.ArgumentParser(description="Generate NUnit tests from YAML spec")
    parser.add_argument("--config", default="config.yaml", help="Path to config file (YAML)")
    args = parser.parse_args()
    
    print("[*] Loading configuration...")
    config = load_config(args.config)
    
    print(f"[*] Loading specification from: {config['spec_path']}")
    spec = load_spec(config["spec_path"])
    
    print("[*] Generating tests...")
    tests_content = generate_all_tests(spec, config)
    
    save_tests(tests_content, config, spec)
    
    print("[√] Generation complete!")

if __name__ == "__main__":
    main()